/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.legacy;

import com.langfuse.client.core.ClientOptions;
import com.langfuse.client.core.Suppliers;
import java.util.function.Supplier;
import com.langfuse.client.resources.legacy.metricsv1.MetricsV1Client;
import com.langfuse.client.resources.legacy.observationsv1.ObservationsV1Client;
import com.langfuse.client.resources.legacy.scorev1.ScoreV1Client;

public class LegacyClient {
  protected final ClientOptions clientOptions;

  protected final Supplier<MetricsV1Client> metricsV1Client;

  protected final Supplier<ObservationsV1Client> observationsV1Client;

  protected final Supplier<ScoreV1Client> scoreV1Client;

  public LegacyClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.metricsV1Client = Suppliers.memoize(() -> new MetricsV1Client(clientOptions));
    this.observationsV1Client = Suppliers.memoize(() -> new ObservationsV1Client(clientOptions));
    this.scoreV1Client = Suppliers.memoize(() -> new ScoreV1Client(clientOptions));
  }

  public MetricsV1Client metricsV1() {
    return this.metricsV1Client.get();
  }

  public ObservationsV1Client observationsV1() {
    return this.observationsV1Client.get();
  }

  public ScoreV1Client scoreV1() {
    return this.scoreV1Client.get();
  }
}
