/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.datasetrunitems;

import com.langfuse.client.core.ClientOptions;
import com.langfuse.client.core.RequestOptions;
import com.langfuse.client.resources.commons.types.DatasetRunItem;
import com.langfuse.client.resources.datasetrunitems.requests.ListDatasetRunItemsRequest;
import com.langfuse.client.resources.datasetrunitems.types.CreateDatasetRunItemRequest;
import com.langfuse.client.resources.datasetrunitems.types.PaginatedDatasetRunItems;

public class DatasetRunItemsClient {
  protected final ClientOptions clientOptions;

  private final RawDatasetRunItemsClient rawClient;

  public DatasetRunItemsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawDatasetRunItemsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawDatasetRunItemsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Create a dataset run item
   */
  public DatasetRunItem create(CreateDatasetRunItemRequest request) {
    return this.rawClient.create(request).body();
  }

  /**
   * Create a dataset run item
   */
  public DatasetRunItem create(CreateDatasetRunItemRequest request, RequestOptions requestOptions) {
    return this.rawClient.create(request, requestOptions).body();
  }

  /**
   * List dataset run items
   */
  public PaginatedDatasetRunItems list(ListDatasetRunItemsRequest request) {
    return this.rawClient.list(request).body();
  }

  /**
   * List dataset run items
   */
  public PaginatedDatasetRunItems list(ListDatasetRunItemsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.list(request, requestOptions).body();
  }
}
