/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.commons.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.langfuse.client.core.Nullable;
import com.langfuse.client.core.NullableNonemptyFilter;
import com.langfuse.client.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = Trace.Builder.class
)
public final class Trace implements ITrace {
  private final String id;

  private final OffsetDateTime timestamp;

  private final Optional<String> name;

  private final Optional<Object> input;

  private final Optional<Object> output;

  private final Optional<String> sessionId;

  private final Optional<String> release;

  private final Optional<String> version;

  private final Optional<String> userId;

  private final Optional<Object> metadata;

  private final List<String> tags;

  private final boolean public_;

  private final String environment;

  private final Map<String, Object> additionalProperties;

  private Trace(String id, OffsetDateTime timestamp, Optional<String> name, Optional<Object> input,
      Optional<Object> output, Optional<String> sessionId, Optional<String> release,
      Optional<String> version, Optional<String> userId, Optional<Object> metadata,
      List<String> tags, boolean public_, String environment,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.timestamp = timestamp;
    this.name = name;
    this.input = input;
    this.output = output;
    this.sessionId = sessionId;
    this.release = release;
    this.version = version;
    this.userId = userId;
    this.metadata = metadata;
    this.tags = tags;
    this.public_ = public_;
    this.environment = environment;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The unique identifier of a trace
   */
  @JsonProperty("id")
  @java.lang.Override
  public String getId() {
    return id;
  }

  /**
   * @return The timestamp when the trace was created
   */
  @JsonProperty("timestamp")
  @java.lang.Override
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  /**
   * @return The name of the trace
   */
  @JsonIgnore
  @java.lang.Override
  public Optional<String> getName() {
    if (name == null) {
      return Optional.empty();
    }
    return name;
  }

  /**
   * @return The input data of the trace. Can be any JSON.
   */
  @JsonProperty("input")
  @java.lang.Override
  public Optional<Object> getInput() {
    return input;
  }

  /**
   * @return The output data of the trace. Can be any JSON.
   */
  @JsonProperty("output")
  @java.lang.Override
  public Optional<Object> getOutput() {
    return output;
  }

  /**
   * @return The session identifier associated with the trace
   */
  @JsonIgnore
  @java.lang.Override
  public Optional<String> getSessionId() {
    if (sessionId == null) {
      return Optional.empty();
    }
    return sessionId;
  }

  /**
   * @return The release version of the application when the trace was created
   */
  @JsonIgnore
  @java.lang.Override
  public Optional<String> getRelease() {
    if (release == null) {
      return Optional.empty();
    }
    return release;
  }

  /**
   * @return The version of the trace
   */
  @JsonIgnore
  @java.lang.Override
  public Optional<String> getVersion() {
    if (version == null) {
      return Optional.empty();
    }
    return version;
  }

  /**
   * @return The user identifier associated with the trace
   */
  @JsonIgnore
  @java.lang.Override
  public Optional<String> getUserId() {
    if (userId == null) {
      return Optional.empty();
    }
    return userId;
  }

  /**
   * @return The metadata associated with the trace. Can be any JSON.
   */
  @JsonProperty("metadata")
  @java.lang.Override
  public Optional<Object> getMetadata() {
    return metadata;
  }

  /**
   * @return The tags associated with the trace.
   */
  @JsonProperty("tags")
  @java.lang.Override
  public List<String> getTags() {
    return tags;
  }

  /**
   * @return Public traces are accessible via url without login
   */
  @JsonProperty("public")
  @java.lang.Override
  public boolean getPublic() {
    return public_;
  }

  /**
   * @return The environment from which this trace originated. Can be any lowercase alphanumeric string with hyphens and underscores that does not start with 'langfuse'.
   */
  @JsonProperty("environment")
  @java.lang.Override
  public String getEnvironment() {
    return environment;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("name")
  private Optional<String> _getName() {
    return name;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("sessionId")
  private Optional<String> _getSessionId() {
    return sessionId;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("release")
  private Optional<String> _getRelease() {
    return release;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("version")
  private Optional<String> _getVersion() {
    return version;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("userId")
  private Optional<String> _getUserId() {
    return userId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof Trace && equalTo((Trace) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(Trace other) {
    return id.equals(other.id) && timestamp.equals(other.timestamp) && name.equals(other.name) && input.equals(other.input) && output.equals(other.output) && sessionId.equals(other.sessionId) && release.equals(other.release) && version.equals(other.version) && userId.equals(other.userId) && metadata.equals(other.metadata) && tags.equals(other.tags) && public_ == other.public_ && environment.equals(other.environment);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.timestamp, this.name, this.input, this.output, this.sessionId, this.release, this.version, this.userId, this.metadata, this.tags, this.public_, this.environment);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    /**
     * <p>The unique identifier of a trace</p>
     */
    TimestampStage id(@NotNull String id);

    Builder from(Trace other);
  }

  public interface TimestampStage {
    /**
     * <p>The timestamp when the trace was created</p>
     */
    PublicStage timestamp(@NotNull OffsetDateTime timestamp);
  }

  public interface PublicStage {
    /**
     * <p>Public traces are accessible via url without login</p>
     */
    EnvironmentStage public_(boolean public_);
  }

  public interface EnvironmentStage {
    /**
     * <p>The environment from which this trace originated. Can be any lowercase alphanumeric string with hyphens and underscores that does not start with 'langfuse'.</p>
     */
    _FinalStage environment(@NotNull String environment);
  }

  public interface _FinalStage {
    Trace build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>The name of the trace</p>
     */
    _FinalStage name(Optional<String> name);

    _FinalStage name(String name);

    _FinalStage name(Nullable<String> name);

    /**
     * <p>The input data of the trace. Can be any JSON.</p>
     */
    _FinalStage input(Optional<Object> input);

    _FinalStage input(Object input);

    /**
     * <p>The output data of the trace. Can be any JSON.</p>
     */
    _FinalStage output(Optional<Object> output);

    _FinalStage output(Object output);

    /**
     * <p>The session identifier associated with the trace</p>
     */
    _FinalStage sessionId(Optional<String> sessionId);

    _FinalStage sessionId(String sessionId);

    _FinalStage sessionId(Nullable<String> sessionId);

    /**
     * <p>The release version of the application when the trace was created</p>
     */
    _FinalStage release(Optional<String> release);

    _FinalStage release(String release);

    _FinalStage release(Nullable<String> release);

    /**
     * <p>The version of the trace</p>
     */
    _FinalStage version(Optional<String> version);

    _FinalStage version(String version);

    _FinalStage version(Nullable<String> version);

    /**
     * <p>The user identifier associated with the trace</p>
     */
    _FinalStage userId(Optional<String> userId);

    _FinalStage userId(String userId);

    _FinalStage userId(Nullable<String> userId);

    /**
     * <p>The metadata associated with the trace. Can be any JSON.</p>
     */
    _FinalStage metadata(Optional<Object> metadata);

    _FinalStage metadata(Object metadata);

    /**
     * <p>The tags associated with the trace.</p>
     */
    _FinalStage tags(List<String> tags);

    _FinalStage addTags(String tags);

    _FinalStage addAllTags(List<String> tags);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, TimestampStage, PublicStage, EnvironmentStage, _FinalStage {
    private String id;

    private OffsetDateTime timestamp;

    private boolean public_;

    private String environment;

    private List<String> tags = new ArrayList<>();

    private Optional<Object> metadata = Optional.empty();

    private Optional<String> userId = Optional.empty();

    private Optional<String> version = Optional.empty();

    private Optional<String> release = Optional.empty();

    private Optional<String> sessionId = Optional.empty();

    private Optional<Object> output = Optional.empty();

    private Optional<Object> input = Optional.empty();

    private Optional<String> name = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(Trace other) {
      id(other.getId());
      timestamp(other.getTimestamp());
      name(other.getName());
      input(other.getInput());
      output(other.getOutput());
      sessionId(other.getSessionId());
      release(other.getRelease());
      version(other.getVersion());
      userId(other.getUserId());
      metadata(other.getMetadata());
      tags(other.getTags());
      public_(other.getPublic());
      environment(other.getEnvironment());
      return this;
    }

    /**
     * <p>The unique identifier of a trace</p>
     * <p>The unique identifier of a trace</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("id")
    public TimestampStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    /**
     * <p>The timestamp when the trace was created</p>
     * <p>The timestamp when the trace was created</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("timestamp")
    public PublicStage timestamp(@NotNull OffsetDateTime timestamp) {
      this.timestamp = Objects.requireNonNull(timestamp, "timestamp must not be null");
      return this;
    }

    /**
     * <p>Public traces are accessible via url without login</p>
     * <p>Public traces are accessible via url without login</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("public")
    public EnvironmentStage public_(boolean public_) {
      this.public_ = public_;
      return this;
    }

    /**
     * <p>The environment from which this trace originated. Can be any lowercase alphanumeric string with hyphens and underscores that does not start with 'langfuse'.</p>
     * <p>The environment from which this trace originated. Can be any lowercase alphanumeric string with hyphens and underscores that does not start with 'langfuse'.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("environment")
    public _FinalStage environment(@NotNull String environment) {
      this.environment = Objects.requireNonNull(environment, "environment must not be null");
      return this;
    }

    /**
     * <p>The tags associated with the trace.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllTags(List<String> tags) {
      if (tags != null) {
        this.tags.addAll(tags);
      }
      return this;
    }

    /**
     * <p>The tags associated with the trace.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addTags(String tags) {
      this.tags.add(tags);
      return this;
    }

    /**
     * <p>The tags associated with the trace.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "tags",
        nulls = Nulls.SKIP
    )
    public _FinalStage tags(List<String> tags) {
      this.tags.clear();
      if (tags != null) {
        this.tags.addAll(tags);
      }
      return this;
    }

    /**
     * <p>The metadata associated with the trace. Can be any JSON.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage metadata(Object metadata) {
      this.metadata = Optional.ofNullable(metadata);
      return this;
    }

    /**
     * <p>The metadata associated with the trace. Can be any JSON.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "metadata",
        nulls = Nulls.SKIP
    )
    public _FinalStage metadata(Optional<Object> metadata) {
      this.metadata = metadata;
      return this;
    }

    /**
     * <p>The user identifier associated with the trace</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage userId(Nullable<String> userId) {
      if (userId.isNull()) {
        this.userId = null;
      }
      else if (userId.isEmpty()) {
        this.userId = Optional.empty();
      }
      else {
        this.userId = Optional.of(userId.get());
      }
      return this;
    }

    /**
     * <p>The user identifier associated with the trace</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage userId(String userId) {
      this.userId = Optional.ofNullable(userId);
      return this;
    }

    /**
     * <p>The user identifier associated with the trace</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "userId",
        nulls = Nulls.SKIP
    )
    public _FinalStage userId(Optional<String> userId) {
      this.userId = userId;
      return this;
    }

    /**
     * <p>The version of the trace</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage version(Nullable<String> version) {
      if (version.isNull()) {
        this.version = null;
      }
      else if (version.isEmpty()) {
        this.version = Optional.empty();
      }
      else {
        this.version = Optional.of(version.get());
      }
      return this;
    }

    /**
     * <p>The version of the trace</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage version(String version) {
      this.version = Optional.ofNullable(version);
      return this;
    }

    /**
     * <p>The version of the trace</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "version",
        nulls = Nulls.SKIP
    )
    public _FinalStage version(Optional<String> version) {
      this.version = version;
      return this;
    }

    /**
     * <p>The release version of the application when the trace was created</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage release(Nullable<String> release) {
      if (release.isNull()) {
        this.release = null;
      }
      else if (release.isEmpty()) {
        this.release = Optional.empty();
      }
      else {
        this.release = Optional.of(release.get());
      }
      return this;
    }

    /**
     * <p>The release version of the application when the trace was created</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage release(String release) {
      this.release = Optional.ofNullable(release);
      return this;
    }

    /**
     * <p>The release version of the application when the trace was created</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "release",
        nulls = Nulls.SKIP
    )
    public _FinalStage release(Optional<String> release) {
      this.release = release;
      return this;
    }

    /**
     * <p>The session identifier associated with the trace</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage sessionId(Nullable<String> sessionId) {
      if (sessionId.isNull()) {
        this.sessionId = null;
      }
      else if (sessionId.isEmpty()) {
        this.sessionId = Optional.empty();
      }
      else {
        this.sessionId = Optional.of(sessionId.get());
      }
      return this;
    }

    /**
     * <p>The session identifier associated with the trace</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage sessionId(String sessionId) {
      this.sessionId = Optional.ofNullable(sessionId);
      return this;
    }

    /**
     * <p>The session identifier associated with the trace</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "sessionId",
        nulls = Nulls.SKIP
    )
    public _FinalStage sessionId(Optional<String> sessionId) {
      this.sessionId = sessionId;
      return this;
    }

    /**
     * <p>The output data of the trace. Can be any JSON.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage output(Object output) {
      this.output = Optional.ofNullable(output);
      return this;
    }

    /**
     * <p>The output data of the trace. Can be any JSON.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "output",
        nulls = Nulls.SKIP
    )
    public _FinalStage output(Optional<Object> output) {
      this.output = output;
      return this;
    }

    /**
     * <p>The input data of the trace. Can be any JSON.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage input(Object input) {
      this.input = Optional.ofNullable(input);
      return this;
    }

    /**
     * <p>The input data of the trace. Can be any JSON.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "input",
        nulls = Nulls.SKIP
    )
    public _FinalStage input(Optional<Object> input) {
      this.input = input;
      return this;
    }

    /**
     * <p>The name of the trace</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage name(Nullable<String> name) {
      if (name.isNull()) {
        this.name = null;
      }
      else if (name.isEmpty()) {
        this.name = Optional.empty();
      }
      else {
        this.name = Optional.of(name.get());
      }
      return this;
    }

    /**
     * <p>The name of the trace</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    /**
     * <p>The name of the trace</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public _FinalStage name(Optional<String> name) {
      this.name = name;
      return this;
    }

    @java.lang.Override
    public Trace build() {
      return new Trace(id, timestamp, name, input, output, sessionId, release, version, userId, metadata, tags, public_, environment, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
