/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.llmconnections;

import com.langfuse.client.core.ClientOptions;
import com.langfuse.client.core.RequestOptions;
import java.util.concurrent.CompletableFuture;
import com.langfuse.client.resources.llmconnections.requests.GetLlmConnectionsRequest;
import com.langfuse.client.resources.llmconnections.types.LlmConnection;
import com.langfuse.client.resources.llmconnections.types.PaginatedLlmConnections;
import com.langfuse.client.resources.llmconnections.types.UpsertLlmConnectionRequest;

public class AsyncLlmConnectionsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawLlmConnectionsClient rawClient;

  public AsyncLlmConnectionsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawLlmConnectionsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawLlmConnectionsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Get all LLM connections in a project
   */
  public CompletableFuture<PaginatedLlmConnections> list() {
    return this.rawClient.list().thenApply(response -> response.body());
  }

  /**
   * Get all LLM connections in a project
   */
  public CompletableFuture<PaginatedLlmConnections> list(RequestOptions requestOptions) {
    return this.rawClient.list(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get all LLM connections in a project
   */
  public CompletableFuture<PaginatedLlmConnections> list(GetLlmConnectionsRequest request) {
    return this.rawClient.list(request).thenApply(response -> response.body());
  }

  /**
   * Get all LLM connections in a project
   */
  public CompletableFuture<PaginatedLlmConnections> list(GetLlmConnectionsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Create or update an LLM connection. The connection is upserted on provider.
   */
  public CompletableFuture<LlmConnection> upsert(UpsertLlmConnectionRequest request) {
    return this.rawClient.upsert(request).thenApply(response -> response.body());
  }

  /**
   * Create or update an LLM connection. The connection is upserted on provider.
   */
  public CompletableFuture<LlmConnection> upsert(UpsertLlmConnectionRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.upsert(request, requestOptions).thenApply(response -> response.body());
  }
}
