/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.scoresv3.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public final class ScoreSubjectV3 {
  private final Value value;

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  private ScoreSubjectV3(Value value) {
    this.value = value;
  }

  public <T> T visit(Visitor<T> visitor) {
    return value.visit(visitor);
  }

  public static ScoreSubjectV3 trace(ScoreSubjectTraceV3 value) {
    return new ScoreSubjectV3(new TraceValue(value));
  }

  public static ScoreSubjectV3 observation(ScoreSubjectObservationV3 value) {
    return new ScoreSubjectV3(new ObservationValue(value));
  }

  public static ScoreSubjectV3 session(ScoreSubjectSessionV3 value) {
    return new ScoreSubjectV3(new SessionValue(value));
  }

  public static ScoreSubjectV3 experiment(ScoreSubjectExperimentV3 value) {
    return new ScoreSubjectV3(new ExperimentValue(value));
  }

  public boolean isTrace() {
    return value instanceof TraceValue;
  }

  public boolean isObservation() {
    return value instanceof ObservationValue;
  }

  public boolean isSession() {
    return value instanceof SessionValue;
  }

  public boolean isExperiment() {
    return value instanceof ExperimentValue;
  }

  public boolean _isUnknown() {
    return value instanceof _UnknownValue;
  }

  public Optional<ScoreSubjectTraceV3> getTrace() {
    if (isTrace()) {
      return Optional.of(((TraceValue) value).value);
    }
    return Optional.empty();
  }

  public Optional<ScoreSubjectObservationV3> getObservation() {
    if (isObservation()) {
      return Optional.of(((ObservationValue) value).value);
    }
    return Optional.empty();
  }

  public Optional<ScoreSubjectSessionV3> getSession() {
    if (isSession()) {
      return Optional.of(((SessionValue) value).value);
    }
    return Optional.empty();
  }

  public Optional<ScoreSubjectExperimentV3> getExperiment() {
    if (isExperiment()) {
      return Optional.of(((ExperimentValue) value).value);
    }
    return Optional.empty();
  }

  public Optional<Object> _getUnknown() {
    if (_isUnknown()) {
      return Optional.of(((_UnknownValue) value).value);
    }
    return Optional.empty();
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ScoreSubjectV3 && value.equals(((ScoreSubjectV3) other).value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public String toString() {
    return value.toString();
  }

  @JsonValue
  private Value getValue() {
    return this.value;
  }

  public interface Visitor<T> {
    T visitTrace(ScoreSubjectTraceV3 trace);

    T visitObservation(ScoreSubjectObservationV3 observation);

    T visitSession(ScoreSubjectSessionV3 session);

    T visitExperiment(ScoreSubjectExperimentV3 experiment);

    T _visitUnknown(Object unknownType);
  }

  @JsonTypeInfo(
      use = JsonTypeInfo.Id.NAME,
      property = "kind",
      visible = true,
      defaultImpl = _UnknownValue.class
  )
  @JsonSubTypes({
      @JsonSubTypes.Type(TraceValue.class),
      @JsonSubTypes.Type(ObservationValue.class),
      @JsonSubTypes.Type(SessionValue.class),
      @JsonSubTypes.Type(ExperimentValue.class)
  })
  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  private interface Value {
    <T> T visit(Visitor<T> visitor);
  }

  @JsonTypeName("trace")
  @JsonIgnoreProperties("kind")
  private static final class TraceValue implements Value {
    @JsonUnwrapped
    @JsonIgnoreProperties(
        value = "kind",
        allowSetters = true
    )
    private ScoreSubjectTraceV3 value;

    @JsonCreator(
        mode = JsonCreator.Mode.PROPERTIES
    )
    private TraceValue() {
    }

    private TraceValue(ScoreSubjectTraceV3 value) {
      this.value = value;
    }

    @java.lang.Override
    public <T> T visit(Visitor<T> visitor) {
      return visitor.visitTrace(value);
    }

    @java.lang.Override
    public boolean equals(Object other) {
      if (this == other) return true;
      return other instanceof TraceValue && equalTo((TraceValue) other);
    }

    private boolean equalTo(TraceValue other) {
      return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
      return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
      return "ScoreSubjectV3{" + "value: " + value + "}";
    }
  }

  @JsonTypeName("observation")
  @JsonIgnoreProperties("kind")
  private static final class ObservationValue implements Value {
    @JsonUnwrapped
    @JsonIgnoreProperties(
        value = "kind",
        allowSetters = true
    )
    private ScoreSubjectObservationV3 value;

    @JsonCreator(
        mode = JsonCreator.Mode.PROPERTIES
    )
    private ObservationValue() {
    }

    private ObservationValue(ScoreSubjectObservationV3 value) {
      this.value = value;
    }

    @java.lang.Override
    public <T> T visit(Visitor<T> visitor) {
      return visitor.visitObservation(value);
    }

    @java.lang.Override
    public boolean equals(Object other) {
      if (this == other) return true;
      return other instanceof ObservationValue && equalTo((ObservationValue) other);
    }

    private boolean equalTo(ObservationValue other) {
      return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
      return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
      return "ScoreSubjectV3{" + "value: " + value + "}";
    }
  }

  @JsonTypeName("session")
  @JsonIgnoreProperties("kind")
  private static final class SessionValue implements Value {
    @JsonUnwrapped
    @JsonIgnoreProperties(
        value = "kind",
        allowSetters = true
    )
    private ScoreSubjectSessionV3 value;

    @JsonCreator(
        mode = JsonCreator.Mode.PROPERTIES
    )
    private SessionValue() {
    }

    private SessionValue(ScoreSubjectSessionV3 value) {
      this.value = value;
    }

    @java.lang.Override
    public <T> T visit(Visitor<T> visitor) {
      return visitor.visitSession(value);
    }

    @java.lang.Override
    public boolean equals(Object other) {
      if (this == other) return true;
      return other instanceof SessionValue && equalTo((SessionValue) other);
    }

    private boolean equalTo(SessionValue other) {
      return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
      return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
      return "ScoreSubjectV3{" + "value: " + value + "}";
    }
  }

  @JsonTypeName("experiment")
  @JsonIgnoreProperties("kind")
  private static final class ExperimentValue implements Value {
    @JsonUnwrapped
    @JsonIgnoreProperties(
        value = "kind",
        allowSetters = true
    )
    private ScoreSubjectExperimentV3 value;

    @JsonCreator(
        mode = JsonCreator.Mode.PROPERTIES
    )
    private ExperimentValue() {
    }

    private ExperimentValue(ScoreSubjectExperimentV3 value) {
      this.value = value;
    }

    @java.lang.Override
    public <T> T visit(Visitor<T> visitor) {
      return visitor.visitExperiment(value);
    }

    @java.lang.Override
    public boolean equals(Object other) {
      if (this == other) return true;
      return other instanceof ExperimentValue && equalTo((ExperimentValue) other);
    }

    private boolean equalTo(ExperimentValue other) {
      return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
      return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
      return "ScoreSubjectV3{" + "value: " + value + "}";
    }
  }

  @JsonIgnoreProperties("kind")
  private static final class _UnknownValue implements Value {
    private String type;

    @JsonValue
    private Object value;

    @JsonCreator(
        mode = JsonCreator.Mode.PROPERTIES
    )
    private _UnknownValue(@JsonProperty("value") Object value) {
    }

    @java.lang.Override
    public <T> T visit(Visitor<T> visitor) {
      return visitor._visitUnknown(value);
    }

    @java.lang.Override
    public boolean equals(Object other) {
      if (this == other) return true;
      return other instanceof _UnknownValue && equalTo((_UnknownValue) other);
    }

    private boolean equalTo(_UnknownValue other) {
      return type.equals(other.type) && value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
      return Objects.hash(this.type, this.value);
    }

    @java.lang.Override
    public String toString() {
      return "ScoreSubjectV3{" + "type: " + type + ", value: " + value + "}";
    }
  }
}
