/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.prompts.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.langfuse.client.core.ObjectMappers;
import java.io.IOException;
import java.lang.IllegalStateException;
import java.lang.Object;
import java.lang.RuntimeException;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Map;
import java.util.Objects;

@JsonDeserialize(
    using = ChatMessageWithPlaceholders.Deserializer.class
)
public final class ChatMessageWithPlaceholders {
  private final Object value;

  private final int type;

  private ChatMessageWithPlaceholders(Object value, int type) {
    this.value = value;
    this.type = type;
  }

  @JsonValue
  public Object get() {
    return this.value;
  }

  @SuppressWarnings("unchecked")
  public <T> T visit(Visitor<T> visitor) {
    if(this.type == 0) {
      return visitor.visit((ChatMessage) this.value);
    } else if(this.type == 1) {
      return visitor.visit((PlaceholderMessage) this.value);
    }
    throw new IllegalStateException("Failed to visit value. This should never happen.");
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ChatMessageWithPlaceholders && equalTo((ChatMessageWithPlaceholders) other);
  }

  private boolean equalTo(ChatMessageWithPlaceholders other) {
    return value.equals(other.value);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.value);
  }

  @java.lang.Override
  public String toString() {
    return this.value.toString();
  }

  public static ChatMessageWithPlaceholders of(ChatMessage value) {
    return new ChatMessageWithPlaceholders(value, 0);
  }

  public static ChatMessageWithPlaceholders of(PlaceholderMessage value) {
    return new ChatMessageWithPlaceholders(value, 1);
  }

  public interface Visitor<T> {
    T visit(ChatMessage value);

    T visit(PlaceholderMessage value);
  }

  static final class Deserializer extends StdDeserializer<ChatMessageWithPlaceholders> {
    Deserializer() {
      super(ChatMessageWithPlaceholders.class);
    }

    @java.lang.Override
    public ChatMessageWithPlaceholders deserialize(JsonParser p, DeserializationContext context)
        throws IOException {
      Object value = p.readValueAs(Object.class);
      // Use "type" discriminator when present — placeholder messages carry
      // "type": "placeholder" while regular chat messages typically have no type field.
      if (value instanceof Map) {
        Map<?, ?> map = (Map<?, ?>) value;
        if ("placeholder".equals(map.get("type"))) {
          try {
            return of(ObjectMappers.JSON_MAPPER.convertValue(value, PlaceholderMessage.class));
          } catch(RuntimeException e) {
          }
        }
      }
      try {
        return of(ObjectMappers.JSON_MAPPER.convertValue(value, ChatMessage.class));
      } catch(RuntimeException e) {
      }
      try {
        return of(ObjectMappers.JSON_MAPPER.convertValue(value, PlaceholderMessage.class));
      } catch(RuntimeException e) {
      }
      throw new JsonParseException(p, "Failed to deserialize");
    }
  }
}
