/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.prompts.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.langfuse.client.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateChatPromptRequest.Builder.class
)
public final class CreateChatPromptRequest {
  private final String name;

  private final List<ChatMessageWithPlaceholders> prompt;

  private final Optional<Object> config;

  private final CreateChatPromptType type;

  private final Optional<List<String>> labels;

  private final Optional<List<String>> tags;

  private final Optional<String> commitMessage;

  private final Map<String, Object> additionalProperties;

  private CreateChatPromptRequest(String name, List<ChatMessageWithPlaceholders> prompt,
      Optional<Object> config, CreateChatPromptType type, Optional<List<String>> labels,
      Optional<List<String>> tags, Optional<String> commitMessage,
      Map<String, Object> additionalProperties) {
    this.name = name;
    this.prompt = prompt;
    this.config = config;
    this.type = type;
    this.labels = labels;
    this.tags = tags;
    this.commitMessage = commitMessage;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonProperty("prompt")
  public List<ChatMessageWithPlaceholders> getPrompt() {
    return prompt;
  }

  @JsonProperty("config")
  public Optional<Object> getConfig() {
    return config;
  }

  @JsonProperty("type")
  public CreateChatPromptType getType() {
    return type;
  }

  /**
   * @return List of deployment labels of this prompt version.
   */
  @JsonProperty("labels")
  public Optional<List<String>> getLabels() {
    return labels;
  }

  /**
   * @return List of tags to apply to all versions of this prompt.
   */
  @JsonProperty("tags")
  public Optional<List<String>> getTags() {
    return tags;
  }

  /**
   * @return Commit message for this prompt version.
   */
  @JsonProperty("commitMessage")
  public Optional<String> getCommitMessage() {
    return commitMessage;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateChatPromptRequest && equalTo((CreateChatPromptRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateChatPromptRequest other) {
    return name.equals(other.name) && prompt.equals(other.prompt) && config.equals(other.config) && type.equals(other.type) && labels.equals(other.labels) && tags.equals(other.tags) && commitMessage.equals(other.commitMessage);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.name, this.prompt, this.config, this.type, this.labels, this.tags, this.commitMessage);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static NameStage builder() {
    return new Builder();
  }

  public interface NameStage {
    TypeStage name(@NotNull String name);

    Builder from(CreateChatPromptRequest other);
  }

  public interface TypeStage {
    _FinalStage type(@NotNull CreateChatPromptType type);
  }

  public interface _FinalStage {
    CreateChatPromptRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage prompt(List<ChatMessageWithPlaceholders> prompt);

    _FinalStage addPrompt(ChatMessageWithPlaceholders prompt);

    _FinalStage addAllPrompt(List<ChatMessageWithPlaceholders> prompt);

    _FinalStage config(Optional<Object> config);

    _FinalStage config(Object config);

    /**
     * <p>List of deployment labels of this prompt version.</p>
     */
    _FinalStage labels(Optional<List<String>> labels);

    _FinalStage labels(List<String> labels);

    /**
     * <p>List of tags to apply to all versions of this prompt.</p>
     */
    _FinalStage tags(Optional<List<String>> tags);

    _FinalStage tags(List<String> tags);

    /**
     * <p>Commit message for this prompt version.</p>
     */
    _FinalStage commitMessage(Optional<String> commitMessage);

    _FinalStage commitMessage(String commitMessage);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements NameStage, TypeStage, _FinalStage {
    private String name;

    private CreateChatPromptType type;

    private Optional<String> commitMessage = Optional.empty();

    private Optional<List<String>> tags = Optional.empty();

    private Optional<List<String>> labels = Optional.empty();

    private Optional<Object> config = Optional.empty();

    private List<ChatMessageWithPlaceholders> prompt = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateChatPromptRequest other) {
      name(other.getName());
      prompt(other.getPrompt());
      config(other.getConfig());
      type(other.getType());
      labels(other.getLabels());
      tags(other.getTags());
      commitMessage(other.getCommitMessage());
      return this;
    }

    @java.lang.Override
    @JsonSetter("name")
    public TypeStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("type")
    public _FinalStage type(@NotNull CreateChatPromptType type) {
      this.type = Objects.requireNonNull(type, "type must not be null");
      return this;
    }

    /**
     * <p>Commit message for this prompt version.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage commitMessage(String commitMessage) {
      this.commitMessage = Optional.ofNullable(commitMessage);
      return this;
    }

    /**
     * <p>Commit message for this prompt version.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "commitMessage",
        nulls = Nulls.SKIP
    )
    public _FinalStage commitMessage(Optional<String> commitMessage) {
      this.commitMessage = commitMessage;
      return this;
    }

    /**
     * <p>List of tags to apply to all versions of this prompt.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage tags(List<String> tags) {
      this.tags = Optional.ofNullable(tags);
      return this;
    }

    /**
     * <p>List of tags to apply to all versions of this prompt.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "tags",
        nulls = Nulls.SKIP
    )
    public _FinalStage tags(Optional<List<String>> tags) {
      this.tags = tags;
      return this;
    }

    /**
     * <p>List of deployment labels of this prompt version.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage labels(List<String> labels) {
      this.labels = Optional.ofNullable(labels);
      return this;
    }

    /**
     * <p>List of deployment labels of this prompt version.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "labels",
        nulls = Nulls.SKIP
    )
    public _FinalStage labels(Optional<List<String>> labels) {
      this.labels = labels;
      return this;
    }

    @java.lang.Override
    public _FinalStage config(Object config) {
      this.config = Optional.ofNullable(config);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "config",
        nulls = Nulls.SKIP
    )
    public _FinalStage config(Optional<Object> config) {
      this.config = config;
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllPrompt(List<ChatMessageWithPlaceholders> prompt) {
      if (prompt != null) {
        this.prompt.addAll(prompt);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addPrompt(ChatMessageWithPlaceholders prompt) {
      this.prompt.add(prompt);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "prompt",
        nulls = Nulls.SKIP
    )
    public _FinalStage prompt(List<ChatMessageWithPlaceholders> prompt) {
      this.prompt.clear();
      if (prompt != null) {
        this.prompt.addAll(prompt);
      }
      return this;
    }

    @java.lang.Override
    public CreateChatPromptRequest build() {
      return new CreateChatPromptRequest(name, prompt, config, type, labels, tags, commitMessage, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
