/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.prompts.types;

import java.lang.Object;
import java.lang.String;
import java.util.List;
import java.util.Optional;

public interface IBasePrompt {
  String getName();

  int getVersion();

  Object getConfig();

  List<String> getLabels();

  List<String> getTags();

  Optional<String> getCommitMessage();
}
