/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.core;

import java.lang.Exception;
import java.lang.RuntimeException;
import java.lang.String;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class LangfuseClientException extends RuntimeException {
  public LangfuseClientException(String message) {
    super(message);
  }

  public LangfuseClientException(String message, Exception e) {
    super(message, e);
  }
}
