/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.promptversion;

import com.langfuse.client.core.ClientOptions;
import com.langfuse.client.core.RequestOptions;
import java.lang.String;
import com.langfuse.client.resources.prompts.types.Prompt;
import com.langfuse.client.resources.promptversion.requests.UpdatePromptRequest;

public class PromptVersionClient {
  protected final ClientOptions clientOptions;

  private final RawPromptVersionClient rawClient;

  public PromptVersionClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawPromptVersionClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawPromptVersionClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Update labels for a specific prompt version
   */
  public Prompt update(String name, int version, UpdatePromptRequest request) {
    return this.rawClient.update(name, version, request).body();
  }

  /**
   * Update labels for a specific prompt version
   */
  public Prompt update(String name, int version, UpdatePromptRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.update(name, version, request, requestOptions).body();
  }
}
