/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.opentelemetry.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.langfuse.client.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = OtelAttribute.Builder.class
)
public final class OtelAttribute {
  private final Optional<String> key;

  private final Optional<OtelAttributeValue> value;

  private final Map<String, Object> additionalProperties;

  private OtelAttribute(Optional<String> key, Optional<OtelAttributeValue> value,
      Map<String, Object> additionalProperties) {
    this.key = key;
    this.value = value;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Attribute key (e.g., &quot;service.name&quot;, &quot;langfuse.observation.type&quot;)
   */
  @JsonProperty("key")
  public Optional<String> getKey() {
    return key;
  }

  /**
   * @return Attribute value
   */
  @JsonProperty("value")
  public Optional<OtelAttributeValue> getValue() {
    return value;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof OtelAttribute && equalTo((OtelAttribute) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(OtelAttribute other) {
    return key.equals(other.key) && value.equals(other.value);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.key, this.value);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> key = Optional.empty();

    private Optional<OtelAttributeValue> value = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(OtelAttribute other) {
      key(other.getKey());
      value(other.getValue());
      return this;
    }

    @JsonSetter(
        value = "key",
        nulls = Nulls.SKIP
    )
    public Builder key(Optional<String> key) {
      this.key = key;
      return this;
    }

    public Builder key(String key) {
      this.key = Optional.ofNullable(key);
      return this;
    }

    @JsonSetter(
        value = "value",
        nulls = Nulls.SKIP
    )
    public Builder value(Optional<OtelAttributeValue> value) {
      this.value = value;
      return this;
    }

    public Builder value(OtelAttributeValue value) {
      this.value = Optional.ofNullable(value);
      return this;
    }

    public OtelAttribute build() {
      return new OtelAttribute(key, value, additionalProperties);
    }
  }
}
