/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.health.errors;

import com.langfuse.client.core.LangfuseClientApiException;
import java.lang.Object;

public final class ServiceUnavailableError extends LangfuseClientApiException {
  public ServiceUnavailableError(Object body) {
    super("ServiceUnavailableError", 503, body);
  }
}
