/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.organizations;

import com.langfuse.client.core.ClientOptions;
import com.langfuse.client.core.RequestOptions;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import com.langfuse.client.resources.organizations.types.DeleteMembershipRequest;
import com.langfuse.client.resources.organizations.types.MembershipDeletionResponse;
import com.langfuse.client.resources.organizations.types.MembershipRequest;
import com.langfuse.client.resources.organizations.types.MembershipResponse;
import com.langfuse.client.resources.organizations.types.MembershipsResponse;
import com.langfuse.client.resources.organizations.types.OrganizationApiKeysResponse;
import com.langfuse.client.resources.organizations.types.OrganizationProjectsResponse;

public class AsyncOrganizationsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawOrganizationsClient rawClient;

  public AsyncOrganizationsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawOrganizationsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawOrganizationsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Get all memberships for the organization associated with the API key (requires organization-scoped API key)
   */
  public CompletableFuture<MembershipsResponse> getOrganizationMemberships() {
    return this.rawClient.getOrganizationMemberships().thenApply(response -> response.body());
  }

  /**
   * Get all memberships for the organization associated with the API key (requires organization-scoped API key)
   */
  public CompletableFuture<MembershipsResponse> getOrganizationMemberships(
      RequestOptions requestOptions) {
    return this.rawClient.getOrganizationMemberships(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Create or update a membership for the organization associated with the API key (requires organization-scoped API key)
   */
  public CompletableFuture<MembershipResponse> updateOrganizationMembership(
      MembershipRequest request) {
    return this.rawClient.updateOrganizationMembership(request).thenApply(response -> response.body());
  }

  /**
   * Create or update a membership for the organization associated with the API key (requires organization-scoped API key)
   */
  public CompletableFuture<MembershipResponse> updateOrganizationMembership(
      MembershipRequest request, RequestOptions requestOptions) {
    return this.rawClient.updateOrganizationMembership(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Delete a membership from the organization associated with the API key (requires organization-scoped API key)
   */
  public CompletableFuture<MembershipDeletionResponse> deleteOrganizationMembership(
      DeleteMembershipRequest request) {
    return this.rawClient.deleteOrganizationMembership(request).thenApply(response -> response.body());
  }

  /**
   * Delete a membership from the organization associated with the API key (requires organization-scoped API key)
   */
  public CompletableFuture<MembershipDeletionResponse> deleteOrganizationMembership(
      DeleteMembershipRequest request, RequestOptions requestOptions) {
    return this.rawClient.deleteOrganizationMembership(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get all memberships for a specific project (requires organization-scoped API key)
   */
  public CompletableFuture<MembershipsResponse> getProjectMemberships(String projectId) {
    return this.rawClient.getProjectMemberships(projectId).thenApply(response -> response.body());
  }

  /**
   * Get all memberships for a specific project (requires organization-scoped API key)
   */
  public CompletableFuture<MembershipsResponse> getProjectMemberships(String projectId,
      RequestOptions requestOptions) {
    return this.rawClient.getProjectMemberships(projectId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Create or update a membership for a specific project (requires organization-scoped API key). The user must already be a member of the organization.
   */
  public CompletableFuture<MembershipResponse> updateProjectMembership(String projectId,
      MembershipRequest request) {
    return this.rawClient.updateProjectMembership(projectId, request).thenApply(response -> response.body());
  }

  /**
   * Create or update a membership for a specific project (requires organization-scoped API key). The user must already be a member of the organization.
   */
  public CompletableFuture<MembershipResponse> updateProjectMembership(String projectId,
      MembershipRequest request, RequestOptions requestOptions) {
    return this.rawClient.updateProjectMembership(projectId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Delete a membership from a specific project (requires organization-scoped API key). The user must be a member of the organization.
   */
  public CompletableFuture<MembershipDeletionResponse> deleteProjectMembership(String projectId,
      DeleteMembershipRequest request) {
    return this.rawClient.deleteProjectMembership(projectId, request).thenApply(response -> response.body());
  }

  /**
   * Delete a membership from a specific project (requires organization-scoped API key). The user must be a member of the organization.
   */
  public CompletableFuture<MembershipDeletionResponse> deleteProjectMembership(String projectId,
      DeleteMembershipRequest request, RequestOptions requestOptions) {
    return this.rawClient.deleteProjectMembership(projectId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get all projects for the organization associated with the API key (requires organization-scoped API key)
   */
  public CompletableFuture<OrganizationProjectsResponse> getOrganizationProjects() {
    return this.rawClient.getOrganizationProjects().thenApply(response -> response.body());
  }

  /**
   * Get all projects for the organization associated with the API key (requires organization-scoped API key)
   */
  public CompletableFuture<OrganizationProjectsResponse> getOrganizationProjects(
      RequestOptions requestOptions) {
    return this.rawClient.getOrganizationProjects(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get all API keys for the organization associated with the API key (requires organization-scoped API key)
   */
  public CompletableFuture<OrganizationApiKeysResponse> getOrganizationApiKeys() {
    return this.rawClient.getOrganizationApiKeys().thenApply(response -> response.body());
  }

  /**
   * Get all API keys for the organization associated with the API key (requires organization-scoped API key)
   */
  public CompletableFuture<OrganizationApiKeysResponse> getOrganizationApiKeys(
      RequestOptions requestOptions) {
    return this.rawClient.getOrganizationApiKeys(requestOptions).thenApply(response -> response.body());
  }
}
