/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.organizations;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.langfuse.client.core.ClientOptions;
import com.langfuse.client.core.LangfuseClientApiException;
import com.langfuse.client.core.LangfuseClientException;
import com.langfuse.client.core.LangfuseClientHttpResponse;
import com.langfuse.client.core.MediaTypes;
import com.langfuse.client.core.ObjectMappers;
import com.langfuse.client.core.RequestOptions;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import com.langfuse.client.resources.commons.errors.AccessDeniedError;
import com.langfuse.client.resources.commons.errors.Error;
import com.langfuse.client.resources.commons.errors.MethodNotAllowedError;
import com.langfuse.client.resources.commons.errors.NotFoundError;
import com.langfuse.client.resources.commons.errors.UnauthorizedError;
import com.langfuse.client.resources.organizations.types.DeleteMembershipRequest;
import com.langfuse.client.resources.organizations.types.MembershipDeletionResponse;
import com.langfuse.client.resources.organizations.types.MembershipRequest;
import com.langfuse.client.resources.organizations.types.MembershipResponse;
import com.langfuse.client.resources.organizations.types.MembershipsResponse;
import com.langfuse.client.resources.organizations.types.OrganizationApiKeysResponse;
import com.langfuse.client.resources.organizations.types.OrganizationProjectsResponse;

public class RawOrganizationsClient {
  protected final ClientOptions clientOptions;

  public RawOrganizationsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Get all memberships for the organization associated with the API key (requires organization-scoped API key)
   */
  public LangfuseClientHttpResponse<MembershipsResponse> getOrganizationMemberships() {
    return getOrganizationMemberships(null);
  }

  /**
   * Get all memberships for the organization associated with the API key (requires organization-scoped API key)
   */
  public LangfuseClientHttpResponse<MembershipsResponse> getOrganizationMemberships(
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
      .addPathSegments("api/public")
      .addPathSegments("organizations/memberships");if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new LangfuseClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, MembershipsResponse.class), response);
        }
        try {
          switch (response.code()) {
            case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new LangfuseClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (IOException e) {
        throw new LangfuseClientException("Network error executing HTTP request", e);
      }
    }

    /**
     * Create or update a membership for the organization associated with the API key (requires organization-scoped API key)
     */
    public LangfuseClientHttpResponse<MembershipResponse> updateOrganizationMembership(
        MembershipRequest request) {
      return updateOrganizationMembership(request,null);
    }

    /**
     * Create or update a membership for the organization associated with the API key (requires organization-scoped API key)
     */
    public LangfuseClientHttpResponse<MembershipResponse> updateOrganizationMembership(
        MembershipRequest request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
        .addPathSegments("api/public")
        .addPathSegments("organizations/memberships");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        RequestBody body;
        try {
          body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        }
        catch(JsonProcessingException e) {
          throw new LangfuseClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
          .url(httpUrl.build())
          .method("PUT", body)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json")
          .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          if (response.isSuccessful()) {
            return new LangfuseClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, MembershipResponse.class), response);
          }
          try {
            switch (response.code()) {
              case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            }
          }
          catch (JsonProcessingException ignored) {
            // unable to map error response, throwing generic error
          }
          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
          throw new LangfuseClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
        }
        catch (IOException e) {
          throw new LangfuseClientException("Network error executing HTTP request", e);
        }
      }

      /**
       * Delete a membership from the organization associated with the API key (requires organization-scoped API key)
       */
      public LangfuseClientHttpResponse<MembershipDeletionResponse> deleteOrganizationMembership(
          DeleteMembershipRequest request) {
        return deleteOrganizationMembership(request,null);
      }

      /**
       * Delete a membership from the organization associated with the API key (requires organization-scoped API key)
       */
      public LangfuseClientHttpResponse<MembershipDeletionResponse> deleteOrganizationMembership(
          DeleteMembershipRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
          .addPathSegments("api/public")
          .addPathSegments("organizations/memberships");if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          RequestBody body;
          try {
            body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
          }
          catch(JsonProcessingException e) {
            throw new LangfuseClientException("Failed to serialize request", e);
          }
          Request okhttpRequest = new Request.Builder()
            .url(httpUrl.build())
            .method("DELETE", body)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json")
            .addHeader("Accept", "application/json")
            .build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              return new LangfuseClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, MembershipDeletionResponse.class), response);
            }
            try {
              switch (response.code()) {
                case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new LangfuseClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
          }
          catch (IOException e) {
            throw new LangfuseClientException("Network error executing HTTP request", e);
          }
        }

        /**
         * Get all memberships for a specific project (requires organization-scoped API key)
         */
        public LangfuseClientHttpResponse<MembershipsResponse> getProjectMemberships(
            String projectId) {
          return getProjectMemberships(projectId,null);
        }

        /**
         * Get all memberships for a specific project (requires organization-scoped API key)
         */
        public LangfuseClientHttpResponse<MembershipsResponse> getProjectMemberships(
            String projectId, RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
            .addPathSegments("api/public")
            .addPathSegments("projects")
            .addPathSegment(projectId)
            .addPathSegments("memberships");if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            Request okhttpRequest = new Request.Builder()
              .url(httpUrl.build())
              .method("GET", null)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Accept", "application/json")
              .build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            try (Response response = client.newCall(okhttpRequest).execute()) {
              ResponseBody responseBody = response.body();
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                return new LangfuseClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, MembershipsResponse.class), response);
              }
              try {
                switch (response.code()) {
                  case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              throw new LangfuseClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
            }
            catch (IOException e) {
              throw new LangfuseClientException("Network error executing HTTP request", e);
            }
          }

          /**
           * Create or update a membership for a specific project (requires organization-scoped API key). The user must already be a member of the organization.
           */
          public LangfuseClientHttpResponse<MembershipResponse> updateProjectMembership(
              String projectId, MembershipRequest request) {
            return updateProjectMembership(projectId,request,null);
          }

          /**
           * Create or update a membership for a specific project (requires organization-scoped API key). The user must already be a member of the organization.
           */
          public LangfuseClientHttpResponse<MembershipResponse> updateProjectMembership(
              String projectId, MembershipRequest request, RequestOptions requestOptions) {
            HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
              .addPathSegments("api/public")
              .addPathSegments("projects")
              .addPathSegment(projectId)
              .addPathSegments("memberships");if (requestOptions != null) {
                requestOptions.getQueryParameters().forEach((_key, _value) -> {
                  httpUrl.addQueryParameter(_key, _value);
                } );
              }
              RequestBody body;
              try {
                body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
              }
              catch(JsonProcessingException e) {
                throw new LangfuseClientException("Failed to serialize request", e);
              }
              Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PUT", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
              OkHttpClient client = clientOptions.httpClient();
              if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
              }
              try (Response response = client.newCall(okhttpRequest).execute()) {
                ResponseBody responseBody = response.body();
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                if (response.isSuccessful()) {
                  return new LangfuseClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, MembershipResponse.class), response);
                }
                try {
                  switch (response.code()) {
                    case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  }
                }
                catch (JsonProcessingException ignored) {
                  // unable to map error response, throwing generic error
                }
                Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                throw new LangfuseClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
              }
              catch (IOException e) {
                throw new LangfuseClientException("Network error executing HTTP request", e);
              }
            }

            /**
             * Delete a membership from a specific project (requires organization-scoped API key). The user must be a member of the organization.
             */
            public LangfuseClientHttpResponse<MembershipDeletionResponse> deleteProjectMembership(
                String projectId, DeleteMembershipRequest request) {
              return deleteProjectMembership(projectId,request,null);
            }

            /**
             * Delete a membership from a specific project (requires organization-scoped API key). The user must be a member of the organization.
             */
            public LangfuseClientHttpResponse<MembershipDeletionResponse> deleteProjectMembership(
                String projectId, DeleteMembershipRequest request, RequestOptions requestOptions) {
              HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
                .addPathSegments("api/public")
                .addPathSegments("projects")
                .addPathSegment(projectId)
                .addPathSegments("memberships");if (requestOptions != null) {
                  requestOptions.getQueryParameters().forEach((_key, _value) -> {
                    httpUrl.addQueryParameter(_key, _value);
                  } );
                }
                RequestBody body;
                try {
                  body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
                }
                catch(JsonProcessingException e) {
                  throw new LangfuseClientException("Failed to serialize request", e);
                }
                Request okhttpRequest = new Request.Builder()
                  .url(httpUrl.build())
                  .method("DELETE", body)
                  .headers(Headers.of(clientOptions.headers(requestOptions)))
                  .addHeader("Content-Type", "application/json")
                  .addHeader("Accept", "application/json")
                  .build();
                OkHttpClient client = clientOptions.httpClient();
                if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                  client = clientOptions.httpClientWithTimeout(requestOptions);
                }
                try (Response response = client.newCall(okhttpRequest).execute()) {
                  ResponseBody responseBody = response.body();
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  if (response.isSuccessful()) {
                    return new LangfuseClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, MembershipDeletionResponse.class), response);
                  }
                  try {
                    switch (response.code()) {
                      case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                      case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                      case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                      case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                      case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    }
                  }
                  catch (JsonProcessingException ignored) {
                    // unable to map error response, throwing generic error
                  }
                  Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                  throw new LangfuseClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                }
                catch (IOException e) {
                  throw new LangfuseClientException("Network error executing HTTP request", e);
                }
              }

              /**
               * Get all projects for the organization associated with the API key (requires organization-scoped API key)
               */
              public LangfuseClientHttpResponse<OrganizationProjectsResponse> getOrganizationProjects(
                  ) {
                return getOrganizationProjects(null);
              }

              /**
               * Get all projects for the organization associated with the API key (requires organization-scoped API key)
               */
              public LangfuseClientHttpResponse<OrganizationProjectsResponse> getOrganizationProjects(
                  RequestOptions requestOptions) {
                HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
                  .addPathSegments("api/public")
                  .addPathSegments("organizations/projects");if (requestOptions != null) {
                    requestOptions.getQueryParameters().forEach((_key, _value) -> {
                      httpUrl.addQueryParameter(_key, _value);
                    } );
                  }
                  Request okhttpRequest = new Request.Builder()
                    .url(httpUrl.build())
                    .method("GET", null)
                    .headers(Headers.of(clientOptions.headers(requestOptions)))
                    .addHeader("Accept", "application/json")
                    .build();
                  OkHttpClient client = clientOptions.httpClient();
                  if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                    client = clientOptions.httpClientWithTimeout(requestOptions);
                  }
                  try (Response response = client.newCall(okhttpRequest).execute()) {
                    ResponseBody responseBody = response.body();
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                      return new LangfuseClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, OrganizationProjectsResponse.class), response);
                    }
                    try {
                      switch (response.code()) {
                        case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                        case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                        case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                        case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                        case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                      }
                    }
                    catch (JsonProcessingException ignored) {
                      // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    throw new LangfuseClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                  }
                  catch (IOException e) {
                    throw new LangfuseClientException("Network error executing HTTP request", e);
                  }
                }

                /**
                 * Get all API keys for the organization associated with the API key (requires organization-scoped API key)
                 */
                public LangfuseClientHttpResponse<OrganizationApiKeysResponse> getOrganizationApiKeys(
                    ) {
                  return getOrganizationApiKeys(null);
                }

                /**
                 * Get all API keys for the organization associated with the API key (requires organization-scoped API key)
                 */
                public LangfuseClientHttpResponse<OrganizationApiKeysResponse> getOrganizationApiKeys(
                    RequestOptions requestOptions) {
                  HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
                    .addPathSegments("api/public")
                    .addPathSegments("organizations/apiKeys");if (requestOptions != null) {
                      requestOptions.getQueryParameters().forEach((_key, _value) -> {
                        httpUrl.addQueryParameter(_key, _value);
                      } );
                    }
                    Request okhttpRequest = new Request.Builder()
                      .url(httpUrl.build())
                      .method("GET", null)
                      .headers(Headers.of(clientOptions.headers(requestOptions)))
                      .addHeader("Accept", "application/json")
                      .build();
                    OkHttpClient client = clientOptions.httpClient();
                    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                      client = clientOptions.httpClientWithTimeout(requestOptions);
                    }
                    try (Response response = client.newCall(okhttpRequest).execute()) {
                      ResponseBody responseBody = response.body();
                      String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                      if (response.isSuccessful()) {
                        return new LangfuseClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, OrganizationApiKeysResponse.class), response);
                      }
                      try {
                        switch (response.code()) {
                          case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                          case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                          case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                          case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                          case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                        }
                      }
                      catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                      }
                      Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                      throw new LangfuseClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                    }
                    catch (IOException e) {
                      throw new LangfuseClientException("Network error executing HTTP request", e);
                    }
                  }
                }
