/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.scores;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.langfuse.client.core.ClientOptions;
import com.langfuse.client.core.LangfuseClientApiException;
import com.langfuse.client.core.LangfuseClientException;
import com.langfuse.client.core.LangfuseClientHttpResponse;
import com.langfuse.client.core.MediaTypes;
import com.langfuse.client.core.ObjectMappers;
import com.langfuse.client.core.QueryStringMapper;
import com.langfuse.client.core.RequestOptions;
import com.langfuse.client.core.RetryInterceptor;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;
import com.langfuse.client.resources.commons.errors.AccessDeniedError;
import com.langfuse.client.resources.commons.errors.Error;
import com.langfuse.client.resources.commons.errors.MethodNotAllowedError;
import com.langfuse.client.resources.commons.errors.NotFoundError;
import com.langfuse.client.resources.commons.errors.UnauthorizedError;
import com.langfuse.client.resources.commons.types.Score;
import com.langfuse.client.resources.scores.requests.GetScoresRequest;
import com.langfuse.client.resources.scores.types.CreateScoreRequest;
import com.langfuse.client.resources.scores.types.CreateScoreResponse;
import com.langfuse.client.resources.scores.types.GetScoresResponse;

public class AsyncRawScoresClient {
  protected final ClientOptions clientOptions;

  public AsyncRawScoresClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Create a score (supports trace, observation, session, and dataset run scores)
   */
  public CompletableFuture<LangfuseClientHttpResponse<CreateScoreResponse>> create(
      CreateScoreRequest request) {
    return create(request,null);
  }

  /**
   * Create a score (supports trace, observation, session, and dataset run scores)
   */
  public CompletableFuture<LangfuseClientHttpResponse<CreateScoreResponse>> create(
      CreateScoreRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
      .addPathSegments("api/public")
      .addPathSegments("scores");if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      RequestBody body;
      try {
        body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
      }
      catch(JsonProcessingException e) {
        throw new LangfuseClientException("Failed to serialize request", e);
      }
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl.build())
        .method("POST", body)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json")
        .addHeader("Accept", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
        okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
      }
      CompletableFuture<LangfuseClientHttpResponse<CreateScoreResponse>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              future.complete(new LangfuseClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CreateScoreResponse.class), response));
              return;
            }
            try {
              switch (response.code()) {
                case 400:future.completeExceptionally(new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
                case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
                case 403:future.completeExceptionally(new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
                case 404:future.completeExceptionally(new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
                case 405:future.completeExceptionally(new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            future.completeExceptionally(new LangfuseClientApiException("Error with status code " + response.code(), response.code(), errorBody, response));
            return;
          }
          catch (JsonProcessingException e) {
            future.completeExceptionally(new LangfuseClientException("Failed to deserialize response: " + e.getMessage(), e));
          }
          catch (IOException e) {
            future.completeExceptionally(new LangfuseClientException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new LangfuseClientException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    /**
     * <strong>Deprecated.</strong> Use <code>GET /api/public/v3/scores</code> instead. This endpoint
     * is no longer available on Langfuse v4 and later.
     * <p>Get a list of scores (supports both trace and session scores)</p>
     */
    public CompletableFuture<LangfuseClientHttpResponse<GetScoresResponse>> getMany() {
      return getMany(GetScoresRequest.builder().build());
    }

    /**
     * <strong>Deprecated.</strong> Use <code>GET /api/public/v3/scores</code> instead. This endpoint
     * is no longer available on Langfuse v4 and later.
     * <p>Get a list of scores (supports both trace and session scores)</p>
     */
    public CompletableFuture<LangfuseClientHttpResponse<GetScoresResponse>> getMany(
        RequestOptions requestOptions) {
      return getMany(GetScoresRequest.builder().build(),requestOptions);
    }

    /**
     * <strong>Deprecated.</strong> Use <code>GET /api/public/v3/scores</code> instead. This endpoint
     * is no longer available on Langfuse v4 and later.
     * <p>Get a list of scores (supports both trace and session scores)</p>
     */
    public CompletableFuture<LangfuseClientHttpResponse<GetScoresResponse>> getMany(
        GetScoresRequest request) {
      return getMany(request,null);
    }

    /**
     * <strong>Deprecated.</strong> Use <code>GET /api/public/v3/scores</code> instead. This endpoint
     * is no longer available on Langfuse v4 and later.
     * <p>Get a list of scores (supports both trace and session scores)</p>
     */
    public CompletableFuture<LangfuseClientHttpResponse<GetScoresResponse>> getMany(
        GetScoresRequest request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
        .addPathSegments("api/public")
        .addPathSegments("v2/scores");if (request.getPage().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "page", request.getPage().get(), false);
        }
        if (request.getLimit().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
        }
        if (request.getUserId().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "userId", request.getUserId().get(), false);
        }
        if (request.getName().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "name", request.getName().get(), false);
        }
        if (request.getFromTimestamp().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "fromTimestamp", request.getFromTimestamp().get(), false);
        }
        if (request.getToTimestamp().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "toTimestamp", request.getToTimestamp().get(), false);
        }
        if (request.getSource().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "source", request.getSource().get(), false);
        }
        if (request.getOperator().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "operator", request.getOperator().get(), false);
        }
        if (request.getValue().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "value", request.getValue().get(), false);
        }
        if (request.getScoreIds().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "scoreIds", request.getScoreIds().get(), false);
        }
        if (request.getConfigId().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "configId", request.getConfigId().get(), false);
        }
        if (request.getSessionId().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "sessionId", request.getSessionId().get(), false);
        }
        if (request.getDatasetRunId().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "datasetRunId", request.getDatasetRunId().get(), false);
        }
        if (request.getTraceId().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "traceId", request.getTraceId().get(), false);
        }
        if (request.getObservationId().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "observationId", request.getObservationId().get(), false);
        }
        if (request.getQueueId().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "queueId", request.getQueueId().get(), false);
        }
        if (request.getDataType().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "dataType", request.getDataType().get(), false);
        }
        if (request.getFields().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "fields", request.getFields().get(), false);
        }
        if (request.getFilter().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "filter", request.getFilter().get(), false);
        }
        if (request.getEnvironment().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "environment", request.getEnvironment().get(), true);
        }
        if (request.getTraceTags().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "traceTags", request.getTraceTags().get(), true);
        }
        if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
          okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
        }
        CompletableFuture<LangfuseClientHttpResponse<GetScoresResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                future.complete(new LangfuseClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GetScoresResponse.class), response));
                return;
              }
              try {
                switch (response.code()) {
                  case 400:future.completeExceptionally(new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                  case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                  case 403:future.completeExceptionally(new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                  case 404:future.completeExceptionally(new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                  case 405:future.completeExceptionally(new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              future.completeExceptionally(new LangfuseClientApiException("Error with status code " + response.code(), response.code(), errorBody, response));
              return;
            }
            catch (JsonProcessingException e) {
              future.completeExceptionally(new LangfuseClientException("Failed to deserialize response: " + e.getMessage(), e));
            }
            catch (IOException e) {
              future.completeExceptionally(new LangfuseClientException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new LangfuseClientException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      /**
       * <strong>Deprecated.</strong> Use <code>GET /api/public/v3/scores</code> with the <code>id</code> filter
       * instead. This endpoint is no longer available on Langfuse v4 and later.
       * <p>Get a score (supports both trace and session scores)</p>
       */
      public CompletableFuture<LangfuseClientHttpResponse<Score>> getById(String scoreId) {
        return getById(scoreId,null);
      }

      /**
       * <strong>Deprecated.</strong> Use <code>GET /api/public/v3/scores</code> with the <code>id</code> filter
       * instead. This endpoint is no longer available on Langfuse v4 and later.
       * <p>Get a score (supports both trace and session scores)</p>
       */
      public CompletableFuture<LangfuseClientHttpResponse<Score>> getById(String scoreId,
          RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
          .addPathSegments("api/public")
          .addPathSegments("v2/scores")
          .addPathSegment(scoreId);if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          Request okhttpRequest = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Accept", "application/json")
            .build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
          }
          CompletableFuture<LangfuseClientHttpResponse<Score>> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                if (response.isSuccessful()) {
                  future.complete(new LangfuseClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Score.class), response));
                  return;
                }
                try {
                  switch (response.code()) {
                    case 400:future.completeExceptionally(new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                    return;
                    case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                    return;
                    case 403:future.completeExceptionally(new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                    return;
                    case 404:future.completeExceptionally(new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                    return;
                    case 405:future.completeExceptionally(new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                    return;
                  }
                }
                catch (JsonProcessingException ignored) {
                  // unable to map error response, throwing generic error
                }
                Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                future.completeExceptionally(new LangfuseClientApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                return;
              }
              catch (JsonProcessingException e) {
                future.completeExceptionally(new LangfuseClientException("Failed to deserialize response: " + e.getMessage(), e));
              }
              catch (IOException e) {
                future.completeExceptionally(new LangfuseClientException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new LangfuseClientException("Network error executing HTTP request", e));
            }
          });
          return future;
        }
      }
