/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.sessions;

import com.langfuse.client.core.ClientOptions;
import com.langfuse.client.core.RequestOptions;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import com.langfuse.client.resources.commons.types.SessionWithTraces;
import com.langfuse.client.resources.sessions.requests.GetSessionsRequest;
import com.langfuse.client.resources.sessions.types.PaginatedSessions;

public class AsyncSessionsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawSessionsClient rawClient;

  public AsyncSessionsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawSessionsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawSessionsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Get sessions.
   * <p>This legacy endpoint is not recommended for new data extraction workflows.
   * Use the v2 observations endpoint with a bounded time range and group rows by
   * <code>sessionId</code> instead:
   * <code>GET /api/public/v2/observations?fromStartTime=&lt;from&gt;&amp;toStartTime=&lt;to&gt;</code>.</p>
   */
  public CompletableFuture<PaginatedSessions> list() {
    return this.rawClient.list().thenApply(response -> response.body());
  }

  /**
   * Get sessions.
   * <p>This legacy endpoint is not recommended for new data extraction workflows.
   * Use the v2 observations endpoint with a bounded time range and group rows by
   * <code>sessionId</code> instead:
   * <code>GET /api/public/v2/observations?fromStartTime=&lt;from&gt;&amp;toStartTime=&lt;to&gt;</code>.</p>
   */
  public CompletableFuture<PaginatedSessions> list(RequestOptions requestOptions) {
    return this.rawClient.list(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get sessions.
   * <p>This legacy endpoint is not recommended for new data extraction workflows.
   * Use the v2 observations endpoint with a bounded time range and group rows by
   * <code>sessionId</code> instead:
   * <code>GET /api/public/v2/observations?fromStartTime=&lt;from&gt;&amp;toStartTime=&lt;to&gt;</code>.</p>
   */
  public CompletableFuture<PaginatedSessions> list(GetSessionsRequest request) {
    return this.rawClient.list(request).thenApply(response -> response.body());
  }

  /**
   * Get sessions.
   * <p>This legacy endpoint is not recommended for new data extraction workflows.
   * Use the v2 observations endpoint with a bounded time range and group rows by
   * <code>sessionId</code> instead:
   * <code>GET /api/public/v2/observations?fromStartTime=&lt;from&gt;&amp;toStartTime=&lt;to&gt;</code>.</p>
   */
  public CompletableFuture<PaginatedSessions> list(GetSessionsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get a session.
   * <p>Please note that <code>traces</code> on this endpoint are not paginated. For large
   * sessions or new data extraction workflows, use the v2 observations endpoint
   * with a URL-encoded <code>sessionId</code> filter and a bounded time range:
   * <code>GET /api/public/v2/observations?filter=&lt;sessionId filter&gt;&amp;fromStartTime=&lt;from&gt;&amp;toStartTime=&lt;to&gt;</code>.</p>
   */
  public CompletableFuture<SessionWithTraces> get(String sessionId) {
    return this.rawClient.get(sessionId).thenApply(response -> response.body());
  }

  /**
   * Get a session.
   * <p>Please note that <code>traces</code> on this endpoint are not paginated. For large
   * sessions or new data extraction workflows, use the v2 observations endpoint
   * with a URL-encoded <code>sessionId</code> filter and a bounded time range:
   * <code>GET /api/public/v2/observations?filter=&lt;sessionId filter&gt;&amp;fromStartTime=&lt;from&gt;&amp;toStartTime=&lt;to&gt;</code>.</p>
   */
  public CompletableFuture<SessionWithTraces> get(String sessionId, RequestOptions requestOptions) {
    return this.rawClient.get(sessionId, requestOptions).thenApply(response -> response.body());
  }
}
