/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.legacy.observationsv1;

import com.langfuse.client.core.ClientOptions;
import com.langfuse.client.core.RequestOptions;
import java.lang.String;
import com.langfuse.client.resources.commons.types.ObservationsViewSingle;
import com.langfuse.client.resources.legacy.observationsv1.requests.GetObservationsRequest;
import com.langfuse.client.resources.legacy.observationsv1.types.ObservationsViews;

public class ObservationsV1Client {
  protected final ClientOptions clientOptions;

  private final RawObservationsV1Client rawClient;

  public ObservationsV1Client(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawObservationsV1Client(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawObservationsV1Client withRawResponse() {
    return this.rawClient;
  }

  /**
   * Get a observation
   */
  public ObservationsViewSingle get(String observationId) {
    return this.rawClient.get(observationId).body();
  }

  /**
   * Get a observation
   */
  public ObservationsViewSingle get(String observationId, RequestOptions requestOptions) {
    return this.rawClient.get(observationId, requestOptions).body();
  }

  /**
   * Get a list of observations.
   * <p>Consider using the <a href="/api-reference#tag/observationsv2/GET/api/public/v2/observations">v2 observations endpoint</a> for cursor-based pagination and field selection.</p>
   */
  public ObservationsViews getMany() {
    return this.rawClient.getMany().body();
  }

  /**
   * Get a list of observations.
   * <p>Consider using the <a href="/api-reference#tag/observationsv2/GET/api/public/v2/observations">v2 observations endpoint</a> for cursor-based pagination and field selection.</p>
   */
  public ObservationsViews getMany(RequestOptions requestOptions) {
    return this.rawClient.getMany(requestOptions).body();
  }

  /**
   * Get a list of observations.
   * <p>Consider using the <a href="/api-reference#tag/observationsv2/GET/api/public/v2/observations">v2 observations endpoint</a> for cursor-based pagination and field selection.</p>
   */
  public ObservationsViews getMany(GetObservationsRequest request) {
    return this.rawClient.getMany(request).body();
  }

  /**
   * Get a list of observations.
   * <p>Consider using the <a href="/api-reference#tag/observationsv2/GET/api/public/v2/observations">v2 observations endpoint</a> for cursor-based pagination and field selection.</p>
   */
  public ObservationsViews getMany(GetObservationsRequest request, RequestOptions requestOptions) {
    return this.rawClient.getMany(request, requestOptions).body();
  }
}
