/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.feedback.errors;

import com.langfuse.client.core.LangfuseClientApiException;
import java.lang.Object;
import okhttp3.Response;

public final class FeedbackNotConfiguredError extends LangfuseClientApiException {
  public FeedbackNotConfiguredError(Object body) {
    super("FeedbackNotConfiguredError", 409, body);
  }

  public FeedbackNotConfiguredError(Object body, Response rawResponse) {
    super("FeedbackNotConfiguredError", 409, body, rawResponse);
  }
}
