/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.commons.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.langfuse.client.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = DatasetItemMediaReferenceMedia.Builder.class
)
public final class DatasetItemMediaReferenceMedia {
  private final String mediaId;

  private final String contentType;

  private final int contentLength;

  private final String url;

  private final String urlExpiry;

  private final Map<String, Object> additionalProperties;

  private DatasetItemMediaReferenceMedia(String mediaId, String contentType, int contentLength,
      String url, String urlExpiry, Map<String, Object> additionalProperties) {
    this.mediaId = mediaId;
    this.contentType = contentType;
    this.contentLength = contentLength;
    this.url = url;
    this.urlExpiry = urlExpiry;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The unique langfuse identifier of the media record
   */
  @JsonProperty("mediaId")
  public String getMediaId() {
    return mediaId;
  }

  /**
   * @return The MIME type of the media record
   */
  @JsonProperty("contentType")
  public String getContentType() {
    return contentType;
  }

  /**
   * @return The size of the media record in bytes
   */
  @JsonProperty("contentLength")
  public int getContentLength() {
    return contentLength;
  }

  /**
   * @return The signed download URL of the media record
   */
  @JsonProperty("url")
  public String getUrl() {
    return url;
  }

  /**
   * @return The expiry date and time of the download URL
   */
  @JsonProperty("urlExpiry")
  public String getUrlExpiry() {
    return urlExpiry;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof DatasetItemMediaReferenceMedia && equalTo((DatasetItemMediaReferenceMedia) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(DatasetItemMediaReferenceMedia other) {
    return mediaId.equals(other.mediaId) && contentType.equals(other.contentType) && contentLength == other.contentLength && url.equals(other.url) && urlExpiry.equals(other.urlExpiry);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.mediaId, this.contentType, this.contentLength, this.url, this.urlExpiry);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static MediaIdStage builder() {
    return new Builder();
  }

  public interface MediaIdStage {
    /**
     * <p>The unique langfuse identifier of the media record</p>
     */
    ContentTypeStage mediaId(@NotNull String mediaId);

    Builder from(DatasetItemMediaReferenceMedia other);
  }

  public interface ContentTypeStage {
    /**
     * <p>The MIME type of the media record</p>
     */
    ContentLengthStage contentType(@NotNull String contentType);
  }

  public interface ContentLengthStage {
    /**
     * <p>The size of the media record in bytes</p>
     */
    UrlStage contentLength(int contentLength);
  }

  public interface UrlStage {
    /**
     * <p>The signed download URL of the media record</p>
     */
    UrlExpiryStage url(@NotNull String url);
  }

  public interface UrlExpiryStage {
    /**
     * <p>The expiry date and time of the download URL</p>
     */
    _FinalStage urlExpiry(@NotNull String urlExpiry);
  }

  public interface _FinalStage {
    DatasetItemMediaReferenceMedia build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements MediaIdStage, ContentTypeStage, ContentLengthStage, UrlStage, UrlExpiryStage, _FinalStage {
    private String mediaId;

    private String contentType;

    private int contentLength;

    private String url;

    private String urlExpiry;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(DatasetItemMediaReferenceMedia other) {
      mediaId(other.getMediaId());
      contentType(other.getContentType());
      contentLength(other.getContentLength());
      url(other.getUrl());
      urlExpiry(other.getUrlExpiry());
      return this;
    }

    /**
     * <p>The unique langfuse identifier of the media record</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("mediaId")
    public ContentTypeStage mediaId(@NotNull String mediaId) {
      this.mediaId = Objects.requireNonNull(mediaId, "mediaId must not be null");
      return this;
    }

    /**
     * <p>The MIME type of the media record</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("contentType")
    public ContentLengthStage contentType(@NotNull String contentType) {
      this.contentType = Objects.requireNonNull(contentType, "contentType must not be null");
      return this;
    }

    /**
     * <p>The size of the media record in bytes</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("contentLength")
    public UrlStage contentLength(int contentLength) {
      this.contentLength = contentLength;
      return this;
    }

    /**
     * <p>The signed download URL of the media record</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("url")
    public UrlExpiryStage url(@NotNull String url) {
      this.url = Objects.requireNonNull(url, "url must not be null");
      return this;
    }

    /**
     * <p>The expiry date and time of the download URL</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("urlExpiry")
    public _FinalStage urlExpiry(@NotNull String urlExpiry) {
      this.urlExpiry = Objects.requireNonNull(urlExpiry, "urlExpiry must not be null");
      return this;
    }

    @java.lang.Override
    public DatasetItemMediaReferenceMedia build() {
      return new DatasetItemMediaReferenceMedia(mediaId, contentType, contentLength, url, urlExpiry, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
