/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.commons.types;

import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Optional;

public interface IBaseScore {
  String getId();

  Optional<String> getTraceId();

  Optional<String> getSessionId();

  Optional<String> getObservationId();

  Optional<String> getDatasetRunId();

  String getName();

  ScoreSource getSource();

  OffsetDateTime getTimestamp();

  OffsetDateTime getCreatedAt();

  OffsetDateTime getUpdatedAt();

  Optional<String> getAuthorUserId();

  Optional<String> getComment();

  Object getMetadata();

  Optional<String> getConfigId();

  Optional<String> getQueueId();

  String getEnvironment();
}
