/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.commons.types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum ScoreDataType {
  NUMERIC("NUMERIC"),

  BOOLEAN("BOOLEAN"),

  CATEGORICAL("CATEGORICAL");

  private final String value;

  ScoreDataType(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
