/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.metrics;

import com.langfuse.client.core.ClientOptions;
import com.langfuse.client.core.RequestOptions;
import com.langfuse.client.resources.metrics.requests.GetMetricsRequest;
import com.langfuse.client.resources.metrics.types.MetricsResponse;

public class MetricsClient {
  protected final ClientOptions clientOptions;

  private final RawMetricsClient rawClient;

  public MetricsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawMetricsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawMetricsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Get metrics from the Langfuse project using a query object.
   * <p>Consider using the <a href="/api-reference#tag/metricsv2/GET/api/public/v2/metrics">v2 metrics endpoint</a> for better performance.</p>
   * <p>For more details, see the <a href="https://langfuse.com/docs/metrics/features/metrics-api">Metrics API documentation</a>.</p>
   */
  public MetricsResponse metrics(GetMetricsRequest request) {
    return this.rawClient.metrics(request).body();
  }

  /**
   * Get metrics from the Langfuse project using a query object.
   * <p>Consider using the <a href="/api-reference#tag/metricsv2/GET/api/public/v2/metrics">v2 metrics endpoint</a> for better performance.</p>
   * <p>For more details, see the <a href="https://langfuse.com/docs/metrics/features/metrics-api">Metrics API documentation</a>.</p>
   */
  public MetricsResponse metrics(GetMetricsRequest request, RequestOptions requestOptions) {
    return this.rawClient.metrics(request, requestOptions).body();
  }
}
