/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.llmconnections.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.langfuse.client.core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = UpsertLlmConnectionRequest.Builder.class
)
public final class UpsertLlmConnectionRequest {
  private final String provider;

  private final LlmAdapter adapter;

  private final String secretKey;

  private final Optional<String> baseUrl;

  private final Optional<List<String>> customModels;

  private final Optional<Boolean> withDefaultModels;

  private final Optional<Map<String, String>> extraHeaders;

  private final Optional<Map<String, Object>> config;

  private final Map<String, Object> additionalProperties;

  private UpsertLlmConnectionRequest(String provider, LlmAdapter adapter, String secretKey,
      Optional<String> baseUrl, Optional<List<String>> customModels,
      Optional<Boolean> withDefaultModels, Optional<Map<String, String>> extraHeaders,
      Optional<Map<String, Object>> config, Map<String, Object> additionalProperties) {
    this.provider = provider;
    this.adapter = adapter;
    this.secretKey = secretKey;
    this.baseUrl = baseUrl;
    this.customModels = customModels;
    this.withDefaultModels = withDefaultModels;
    this.extraHeaders = extraHeaders;
    this.config = config;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Provider name (e.g., 'openai', 'my-gateway'). Must be unique in project, used for upserting.
   */
  @JsonProperty("provider")
  public String getProvider() {
    return provider;
  }

  /**
   * @return The adapter used to interface with the LLM
   */
  @JsonProperty("adapter")
  public LlmAdapter getAdapter() {
    return adapter;
  }

  /**
   * @return Secret key for the LLM API.
   */
  @JsonProperty("secretKey")
  public String getSecretKey() {
    return secretKey;
  }

  /**
   * @return Custom base URL for the LLM API
   */
  @JsonProperty("baseURL")
  public Optional<String> getBaseUrl() {
    return baseUrl;
  }

  /**
   * @return List of custom model names
   */
  @JsonProperty("customModels")
  public Optional<List<String>> getCustomModels() {
    return customModels;
  }

  /**
   * @return Whether to include default models. Default is true.
   */
  @JsonProperty("withDefaultModels")
  public Optional<Boolean> getWithDefaultModels() {
    return withDefaultModels;
  }

  /**
   * @return Extra headers to send with requests
   */
  @JsonProperty("extraHeaders")
  public Optional<Map<String, String>> getExtraHeaders() {
    return extraHeaders;
  }

  /**
   * @return Adapter-specific configuration. Validation rules: - <strong>Bedrock</strong>: Required. Must be <code>{&quot;region&quot;: &quot;&lt;aws-region&gt;&quot;}</code> (e.g., <code>{&quot;region&quot;:&quot;us-east-1&quot;}</code>) - <strong>VertexAI</strong>: Optional. If provided, must be <code>{&quot;location&quot;: &quot;&lt;gcp-location&gt;&quot;}</code> (e.g., <code>{&quot;location&quot;:&quot;us-central1&quot;}</code>) - <strong>Other adapters</strong>: Not supported. Omit this field or set to null.
   */
  @JsonProperty("config")
  public Optional<Map<String, Object>> getConfig() {
    return config;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof UpsertLlmConnectionRequest && equalTo((UpsertLlmConnectionRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(UpsertLlmConnectionRequest other) {
    return provider.equals(other.provider) && adapter.equals(other.adapter) && secretKey.equals(other.secretKey) && baseUrl.equals(other.baseUrl) && customModels.equals(other.customModels) && withDefaultModels.equals(other.withDefaultModels) && extraHeaders.equals(other.extraHeaders) && config.equals(other.config);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.provider, this.adapter, this.secretKey, this.baseUrl, this.customModels, this.withDefaultModels, this.extraHeaders, this.config);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ProviderStage builder() {
    return new Builder();
  }

  public interface ProviderStage {
    /**
     * <p>Provider name (e.g., 'openai', 'my-gateway'). Must be unique in project, used for upserting.</p>
     */
    AdapterStage provider(@NotNull String provider);

    Builder from(UpsertLlmConnectionRequest other);
  }

  public interface AdapterStage {
    /**
     * <p>The adapter used to interface with the LLM</p>
     */
    SecretKeyStage adapter(@NotNull LlmAdapter adapter);
  }

  public interface SecretKeyStage {
    /**
     * <p>Secret key for the LLM API.</p>
     */
    _FinalStage secretKey(@NotNull String secretKey);
  }

  public interface _FinalStage {
    UpsertLlmConnectionRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Custom base URL for the LLM API</p>
     */
    _FinalStage baseUrl(Optional<String> baseUrl);

    _FinalStage baseUrl(String baseUrl);

    /**
     * <p>List of custom model names</p>
     */
    _FinalStage customModels(Optional<List<String>> customModels);

    _FinalStage customModels(List<String> customModels);

    /**
     * <p>Whether to include default models. Default is true.</p>
     */
    _FinalStage withDefaultModels(Optional<Boolean> withDefaultModels);

    _FinalStage withDefaultModels(Boolean withDefaultModels);

    /**
     * <p>Extra headers to send with requests</p>
     */
    _FinalStage extraHeaders(Optional<Map<String, String>> extraHeaders);

    _FinalStage extraHeaders(Map<String, String> extraHeaders);

    /**
     * <p>Adapter-specific configuration. Validation rules: - <strong>Bedrock</strong>: Required. Must be <code>{&quot;region&quot;: &quot;&lt;aws-region&gt;&quot;}</code> (e.g., <code>{&quot;region&quot;:&quot;us-east-1&quot;}</code>) - <strong>VertexAI</strong>: Optional. If provided, must be <code>{&quot;location&quot;: &quot;&lt;gcp-location&gt;&quot;}</code> (e.g., <code>{&quot;location&quot;:&quot;us-central1&quot;}</code>) - <strong>Other adapters</strong>: Not supported. Omit this field or set to null.</p>
     */
    _FinalStage config(Optional<Map<String, Object>> config);

    _FinalStage config(Map<String, Object> config);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ProviderStage, AdapterStage, SecretKeyStage, _FinalStage {
    private String provider;

    private LlmAdapter adapter;

    private String secretKey;

    private Optional<Map<String, Object>> config = Optional.empty();

    private Optional<Map<String, String>> extraHeaders = Optional.empty();

    private Optional<Boolean> withDefaultModels = Optional.empty();

    private Optional<List<String>> customModels = Optional.empty();

    private Optional<String> baseUrl = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(UpsertLlmConnectionRequest other) {
      provider(other.getProvider());
      adapter(other.getAdapter());
      secretKey(other.getSecretKey());
      baseUrl(other.getBaseUrl());
      customModels(other.getCustomModels());
      withDefaultModels(other.getWithDefaultModels());
      extraHeaders(other.getExtraHeaders());
      config(other.getConfig());
      return this;
    }

    /**
     * <p>Provider name (e.g., 'openai', 'my-gateway'). Must be unique in project, used for upserting.</p>
     * <p>Provider name (e.g., 'openai', 'my-gateway'). Must be unique in project, used for upserting.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("provider")
    public AdapterStage provider(@NotNull String provider) {
      this.provider = Objects.requireNonNull(provider, "provider must not be null");
      return this;
    }

    /**
     * <p>The adapter used to interface with the LLM</p>
     * <p>The adapter used to interface with the LLM</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("adapter")
    public SecretKeyStage adapter(@NotNull LlmAdapter adapter) {
      this.adapter = Objects.requireNonNull(adapter, "adapter must not be null");
      return this;
    }

    /**
     * <p>Secret key for the LLM API.</p>
     * <p>Secret key for the LLM API.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("secretKey")
    public _FinalStage secretKey(@NotNull String secretKey) {
      this.secretKey = Objects.requireNonNull(secretKey, "secretKey must not be null");
      return this;
    }

    /**
     * <p>Adapter-specific configuration. Validation rules: - <strong>Bedrock</strong>: Required. Must be <code>{&quot;region&quot;: &quot;&lt;aws-region&gt;&quot;}</code> (e.g., <code>{&quot;region&quot;:&quot;us-east-1&quot;}</code>) - <strong>VertexAI</strong>: Optional. If provided, must be <code>{&quot;location&quot;: &quot;&lt;gcp-location&gt;&quot;}</code> (e.g., <code>{&quot;location&quot;:&quot;us-central1&quot;}</code>) - <strong>Other adapters</strong>: Not supported. Omit this field or set to null.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage config(Map<String, Object> config) {
      this.config = Optional.ofNullable(config);
      return this;
    }

    /**
     * <p>Adapter-specific configuration. Validation rules: - <strong>Bedrock</strong>: Required. Must be <code>{&quot;region&quot;: &quot;&lt;aws-region&gt;&quot;}</code> (e.g., <code>{&quot;region&quot;:&quot;us-east-1&quot;}</code>) - <strong>VertexAI</strong>: Optional. If provided, must be <code>{&quot;location&quot;: &quot;&lt;gcp-location&gt;&quot;}</code> (e.g., <code>{&quot;location&quot;:&quot;us-central1&quot;}</code>) - <strong>Other adapters</strong>: Not supported. Omit this field or set to null.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "config",
        nulls = Nulls.SKIP
    )
    public _FinalStage config(Optional<Map<String, Object>> config) {
      this.config = config;
      return this;
    }

    /**
     * <p>Extra headers to send with requests</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage extraHeaders(Map<String, String> extraHeaders) {
      this.extraHeaders = Optional.ofNullable(extraHeaders);
      return this;
    }

    /**
     * <p>Extra headers to send with requests</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "extraHeaders",
        nulls = Nulls.SKIP
    )
    public _FinalStage extraHeaders(Optional<Map<String, String>> extraHeaders) {
      this.extraHeaders = extraHeaders;
      return this;
    }

    /**
     * <p>Whether to include default models. Default is true.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage withDefaultModels(Boolean withDefaultModels) {
      this.withDefaultModels = Optional.ofNullable(withDefaultModels);
      return this;
    }

    /**
     * <p>Whether to include default models. Default is true.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "withDefaultModels",
        nulls = Nulls.SKIP
    )
    public _FinalStage withDefaultModels(Optional<Boolean> withDefaultModels) {
      this.withDefaultModels = withDefaultModels;
      return this;
    }

    /**
     * <p>List of custom model names</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage customModels(List<String> customModels) {
      this.customModels = Optional.ofNullable(customModels);
      return this;
    }

    /**
     * <p>List of custom model names</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "customModels",
        nulls = Nulls.SKIP
    )
    public _FinalStage customModels(Optional<List<String>> customModels) {
      this.customModels = customModels;
      return this;
    }

    /**
     * <p>Custom base URL for the LLM API</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage baseUrl(String baseUrl) {
      this.baseUrl = Optional.ofNullable(baseUrl);
      return this;
    }

    /**
     * <p>Custom base URL for the LLM API</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "baseURL",
        nulls = Nulls.SKIP
    )
    public _FinalStage baseUrl(Optional<String> baseUrl) {
      this.baseUrl = baseUrl;
      return this;
    }

    @java.lang.Override
    public UpsertLlmConnectionRequest build() {
      return new UpsertLlmConnectionRequest(provider, adapter, secretKey, baseUrl, customModels, withDefaultModels, extraHeaders, config, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
