/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.langfuse.client.resources.comments;

import com.langfuse.client.core.ClientOptions;
import com.langfuse.client.core.RequestOptions;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import com.langfuse.client.resources.comments.requests.GetCommentsRequest;
import com.langfuse.client.resources.comments.types.CreateCommentRequest;
import com.langfuse.client.resources.comments.types.CreateCommentResponse;
import com.langfuse.client.resources.comments.types.GetCommentsResponse;
import com.langfuse.client.resources.commons.types.Comment;

public class AsyncCommentsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawCommentsClient rawClient;

  public AsyncCommentsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawCommentsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawCommentsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Create a comment. Comments may be attached to different object types (trace, observation, session, prompt).
   */
  public CompletableFuture<CreateCommentResponse> create(CreateCommentRequest request) {
    return this.rawClient.create(request).thenApply(response -> response.body());
  }

  /**
   * Create a comment. Comments may be attached to different object types (trace, observation, session, prompt).
   */
  public CompletableFuture<CreateCommentResponse> create(CreateCommentRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get all comments
   */
  public CompletableFuture<GetCommentsResponse> get() {
    return this.rawClient.get().thenApply(response -> response.body());
  }

  /**
   * Get all comments
   */
  public CompletableFuture<GetCommentsResponse> get(RequestOptions requestOptions) {
    return this.rawClient.get(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get all comments
   */
  public CompletableFuture<GetCommentsResponse> get(GetCommentsRequest request) {
    return this.rawClient.get(request).thenApply(response -> response.body());
  }

  /**
   * Get all comments
   */
  public CompletableFuture<GetCommentsResponse> get(GetCommentsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.get(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get a comment by id
   */
  public CompletableFuture<Comment> getById(String commentId) {
    return this.rawClient.getById(commentId).thenApply(response -> response.body());
  }

  /**
   * Get a comment by id
   */
  public CompletableFuture<Comment> getById(String commentId, RequestOptions requestOptions) {
    return this.rawClient.getById(commentId, requestOptions).thenApply(response -> response.body());
  }
}
